@baseURL = http://localhost:3000/
@resourceName = categories

#Categories

# @name getAll
GET {{baseURL}}/{{resourceName}}

###

# @name addNew
POST {{baseURL}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Tủ lạnh"
}

###

# @name update
PATCH {{baseURL}}/{{resourceName}}/iZNWmHb
Content-Type: application/json

{
  "name": "Tủ lạnh cũ"
}

###

# @name remove
DELETE {{baseURL}}/{{resourceName}}/iZNWmHb
Content-Type: application/json

{
  "name": "Tủ lạnh cũ"
}